on:
  push:
    branches:
    - master
name: Build and push to docker hub
jobs:
  BuildAndPush:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to dockerhub
      run: |
        docker version
        docker build -t hitian/ss-v2ray-plugin:latest .
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker push hitian/ss-v2ray-plugin
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
